"""Ad atteept №1

Revision ID: 0b0b199c282d
Revises: ca3a4e8dff9d
Create Date: 2025-11-21 01:39:19.736497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0b199c282d'
down_revision = 'ca3a4e8dff9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_id'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('category_id'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
