"""add disciplines and categories table

Revision ID: 2856a28bd21d
Revises: 8f029bbf7f81
Create Date: 2025-12-09 13:10:01.472159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856a28bd21d'
down_revision = '8f029bbf7f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_discipline_categories_name'))
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['discipline_categories.id'], name=op.f('fk_disciplines_category_id_discipline_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_disciplines_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplines'))
    )
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.drop_table('disciplines')
    op.drop_table('discipline_categories')
    # ### end Alembic commands ###
