"""add image, about_me and last_seen to users

Revision ID: 8f029bbf7f81
Revises: 7b490b70f244
Create Date: 2025-12-05 03:29:47.729599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f029bbf7f81'
down_revision = '7b490b70f244'
branch_labels = None
depends_on = None


def upgrade():
    # ...
    with op.batch_alter_table('users', schema=None) as batch_op:
        # ЗМІНА 1: Додаємо server_default
        batch_op.add_column(sa.Column('image', sa.String(length=20), nullable=False, server_default='profile_default.jpg'))
        
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        
        # ЗМІНА 2: Ставимо nullable=True
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ...


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
